version: 0.2

env:
    parameter-store:
        S3_BUCKET: "dotnet-image-recognition"
phases:
  install:
    commands:
      - dotnet tool install -g Amazon.Lambda.Tools
  build:
    commands:
      - cd ./dotnet-lambda-refarch-imagerecognition/lambda-functions
      - dotnet lambda package-ci --serverless-template serverless.template --output-template updated.template --s3-bucket $S3_BUCKET --s3-prefix image-recognition/lambda-functions
artifacts:
  files:
    - ./dotnet-lambda-refarch-imagerecognition/lambda-functions/updated.template
  discard-paths: yes