version: 0.2

env:
    parameter-store:
        S3_BUCKET: "/ImageRecognition/ImageRecognitionArtifactStore"
phases:
  install:
    commands:
      - dotnet tool install -g Amazon.Lambda.Tools
  build:
    commands:
      - cd ./Application/StepFunctions
      - dotnet lambda package-ci --serverless-template serverless.template --output-template updated.template --s3-bucket $S3_BUCKET --s3-prefix StepFunctions
artifacts:
  files:
    - ./Application/StepFunctions/updated.template
  discard-paths: yes